Refactored: project structure
kairoslav/taxi-price pull request #29
Opened 2021-10-29 21:46 UTC by kairoslav

Added: aggregation of services

2021-10-30 15:12 UTC, kairoslav commented
@Imsamaboy когда уже посмотришь?

2021-10-30 15:14 UTC, Imsamaboy commented
Я же прокомментил

2021-10-30 15:15 UTC, kairoslav commented
> Я же прокомментил 

Нету твоих комментариев

2021-10-30 18:38 UTC, kairoslav commented on app.py
> +# не удалять ни в коем случае
Бот ломается и не отвечает на сообщения

2021-10-30 18:39 UTC, kairoslav commented on services/subway/json_subway_maker.py
> +    with open("../data/reserve_subway_list.json", "w") as json_file:
Так, стоп, я видимо забыл тоже это пофиксить

2021-10-30 18:40 UTC, kairoslav commented on services/taxi/__init__.py
> -from . import yandex_taxi
Видимо не нужно, я хз почему

2021-10-30 18:42 UTC, kairoslav commented on data/config.py
> -YANDEX_TAXI_URL = "https://taxi-routeinfo.taxi.yandex.net/taxi_info"
Ну хз.. на подумать

2021-10-30 18:43 UTC, kairoslav commented on data/config.py
> +ROOT_DIR = pathlib.PurePath(os.path.dirname(os.path.abspath(__file__))).parent
Спиздил эту тему из джанги, узнал много нового про пути в питоне, могу рассказать на досуге почему пришлось именно так делать

2021-10-30 18:46 UTC, kairoslav commented on services/taxi/uber.py
> -            },
Я кстати не знаю почему уюер изменился, надо перепроверить

2021-10-31 11:48 UTC, kairoslav commented
добавил match case с 10 питона
я случайно

2021-10-31 12:39 UTC, Imsamaboy commented on services/taxi/__init__.py
> -from . import yandex_taxi
Ты просто переименовал файлы в citymobil_for_mobile_app и яндекс соответственно

2021-10-31 16:55 UTC, Imsamaboy requested changes

2021-10-31 16:55 UTC, Imsamaboy commented on services/taxi/uber.py
> -            },
Проверил?

2021-10-31 16:55 UTC, Imsamaboy commented on handlers/users/route.py
> +    for response in service_responses:
Хорошо!

2021-11-09 18:35 UTC, kairoslav commented on services/utils.py
>              return None
Этого стиля нет, я наебывал видимо тебя все это время. Это делается так ```except (TypeError, ValueError):```

2021-11-15 19:58 UTC, Imsamaboy requested changes
Сделать: 
Правильно стянуть ветку метро и ответить на вопрос про изменение бади запросов в такси

2021-11-15 19:58 UTC, Imsamaboy commented on Dockerfile
> +ENTRYPOINT ["python", "app.py"]
ок

2021-11-15 19:58 UTC, Imsamaboy commented on models/carsharing_model.py
> +    longitude: int | float
ок

2021-11-15 19:58 UTC, Imsamaboy commented on models/price.py
> +    price: int | float
ок

2021-11-15 19:58 UTC, Imsamaboy commented on requirements.txt
> +loguru~=0.5.3
супер

2021-11-15 19:58 UTC, Imsamaboy commented on services/carsharing/carsharing_service.py
> +            result_string += f"Местоположение: {await get_name_from_coordinates(latitude=carsharing.latitude, longitude=carsharing.longitude)}"
Супер

2021-11-15 19:58 UTC, Imsamaboy commented on services/carsharing/delimobil.py
> +        return None
Хорошо!

2021-11-15 19:58 UTC, Imsamaboy commented on services/carsharing/delimobil.py
> +        return current_price
Наверное, супер!

2021-11-15 19:58 UTC, Imsamaboy commented on services/carsharing/delimobil.py
> +    )
Ок

2021-11-15 19:58 UTC, Imsamaboy commented on services/geocoder/geocoder.py
> +async def get_name_from_coordinates(latitude: str | float, longitude: str | float):
Супер

2021-11-15 19:58 UTC, Imsamaboy commented on services/service.py
> +async def get_response(points: list[Location], flag: bool) -> list[str]:
Класс

2021-11-15 19:58 UTC, Imsamaboy commented on services/subway/subway_service.py
> -            if station['time'] % 10 in (5, 6, 7, 8, 9, 0):
Куда пропало?

2021-11-15 19:58 UTC, Imsamaboy commented on services/taxi/indriver.py
> +    try:
Везде ок

2021-11-15 19:58 UTC, Imsamaboy commented on services/taxi/tests.py
> +                print(await make_request(points))
Скипнул пока, раз валидация ещё не была придумана

2021-11-15 19:58 UTC, Imsamaboy commented on services/taxi/uber.py
> -            },
Ответа не последовало...

2021-11-15 19:58 UTC, Imsamaboy commented on services/utils.py
> +def get_distance(latitude_1: float | str,
Хорошо

2021-11-15 20:02 UTC, kairoslav commented on services/taxi/uber.py
> -            },
мой ответ заключается в том что я нихера не понял что изменилось, но оно продолжает работать

2021-11-15 21:00 UTC, kairoslav commented on services/subway/subway_service.py
> -            if station['time'] % 10 in (5, 6, 7, 8, 9, 0):
скрипя жопой об асфальт поправил

2021-11-16 11:27 UTC, kairoslav commented
@Imsamaboy i'm waiting for your review

2021-11-16 14:46 UTC, Imsamaboy approved these changes

2021-11-16 14:46 UTC, Imsamaboy commented on services/carsharing/delimobil.py
> +            return await resp.json()
Ok

2021-11-16 14:46 UTC, Imsamaboy commented on services/subway/subway_service.py
> +            raise SubwayError()
Ok

2021-11-16 14:46 UTC, Imsamaboy commented on services/carsharing/delimobil.py
> +    return Carsharing(
Пойдёт

2021-11-16 14:46 UTC, Imsamaboy commented on services/carsharing/carsharing_service.py
> +
Норм

2021-11-16 14:49 UTC, merged

2021-11-16 14:55 UTC, kairoslav commented
Siiiiiiiuuuuuuuuuuuuuuuuuuu!